server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docmate
    username: docmate_admin 
    password: docmate_admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
